name: Build
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-22.04, windows-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm install
      
      - name: Update OSS Licenses
        run: |
          npm install -g license-report
          license-report --only=prod --json > frontend/license/frontend.json
          cargo install cargo-license
          cd src-tauri && cargo license -j --direct-deps-only --avoid-dev-deps --avoid-build-deps > ../frontend/license/backend.json

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
      
      - name: Deploy (ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: note.rs_${{runner.os}}
          path: 'src-tauri/target/release/bundle/appimage/*.AppImage'

      - name: Deploy (windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: note.rs_${{runner.os}}
          path: 'src-tauri/target/release/bundle/msi/*.msi'
