name: Vulnerability-Scan
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  audit:
    name: Audit packages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Audit packages
        run: npm audit --audit-level low